UPDATE movies
SET 
  agreement_end_date = COALESCE(agreement_end_date, '3099-12-31')
WHERE LOWER(title) IN (
  'aami aar amar girlfriends',
  'aborto',
  'agni yudha',
  'agnisakshi',
  'amar bodyguard',
  'amar sanghee',
  'ami achi sei je tomar',
  'ami o amar madhuri',
  'ami vs tumi',
  'antarleen',
  'atal jaler ahwan',
  'babu mosai',
  'bazee-the challenge',
  'bhakter maa',
  'bhooter bhobishyot',
  'bhoy',
  'bibhas',
  'bobbyr bondhura',
  'boudi.com',
  'bromhodoityo',
  'chaitali',
  'char adhyay',
  'chaya surya',
  'cycle balok',
  'debi baran',
  'deepar prem',
  'diet',
  'durga sohay',
  'dwiragaman',
  'eai mon tomay deachi',
  'ek jhank ichhe dana',
  'ek tukro agun',
  'encounter',
  'fight 1:1',
  'gharer bairey ghar',
  'gate 2 gether',
  'hanabari',
  'golemale pirit koro na',
  'hiralal',
  'janmadata',
  'jamai no 1',
  'jiban niye khela',
  'kanch kata hirey',
  'karunamoyee',
  'kalpurush',
  'kellafate',
  'krishna',
  'mahanagar @ kolkata',
  'mon chaye tomay',
  'nabangsha',
  'nai babhichar',
  'nater guru',
  'neel rajar deshe',
  'network',
  'ogo badhu sundari',
  'nishachar',
  'pratidwandi',
  'pratidwandi (2010)',
  'raja saheb',
  'raja babu',
  'rajnandini',
  'ram laxman',
  'rann',
  'saat pake bandha (1963)',
  'rehmat ali',
  'sakaler rang',
  'sangee',
  'saptami',
  'sathi amaar bondhu amar',
  'shashi babur sansar',
  'shesh bichar',
  'shesh porjonto',
  'shokal sandhya',
  'shradanjali',
  'shyam saheb',
  'sita',
  'sonar sansar',
  'superstar - love story',
  'surya',
  'swarna sikhar prangane',
  'swapnerdin',
  'tara',
  'tui je amar',
  'tushagni',
  'uttar meleni',
  'zombiesathaan',
  'buro sadhu',
  'tulkalam',
  'windows connection',
  'toofan'
);

UPDATE movies
SET 
  satellite_rights_end_date = COALESCE(satellite_rights_end_date, '3099-12-31'),
  internet_rights_end_date = COALESCE(internet_rights_end_date, '3099-12-31')
WHERE LOWER(title) IN (
  'agni yudha',
  'eai mon tomay deachi',
  'ek jhank ichhe dana',
  'jamai no 1',
  'mon chaye tomay',
  'nabangsha',
  'rann',
  'toofan'
);